### ISSUE TITLE
Challenge1, categorical features

### ISSUE THREAD

**Issue by taka1008** [macss-uml/General-Questions#1]
Hi.  I am trying Challenge1, and have a question about it.

1. Can we think the categorical variable is equivalent to the factorial variable? In other words, can we select the variables which type is "factor" for Q1? I found this article(https://www.guru99.com/r-factor-categorical-continuous.html), but I am not sure if it is right.

Although this may be fundamental questions, I would appreciate if you give me any advice.

Takayuki Kitamura

**Comment by pdwaggoner** [comment]
Hi @taka1008 - thanks for the question. Yes, your understanding in this scenario is correct: you may treat categorical as factor (*not* "factorial", though as you mentioned; but I think you meant *factor*) for this challenge.

**Comment by taka1008** [comment]
Thank you, professor!

Sorry for bothering again. Q1 says that "Create a sparse matrix .... . Then drop SurveyYr and Race3." May we drop two columns from the dataframe, and then create sparse matrix? If not, could you please tell me how to drop two columns from sparse matrix? I googled the way to drop columns from a sparse matrix, but I cannot find it....
