### ISSUE TITLE
Distinguish the same variables

### ISSUE THREAD

**Issue by taka1008** [macss-uml/General-Questions#2]
Hi. I would like to make sure if I am on the right track for Challenge1.

There are same variables in the different columns like Yes/No in "SmokeNow", "Smoke100", and other columns in the dataset.
We should add something to distinguish them in the sparse matrix such as  "SmokeNow_Yes", "Smoke100_Yes", and so on?

Or does the transaction function distinguish automatically? 

Sorry for bothering again. I am looking forward to your reply. Thank you.

**Comment by pdwaggoner** [comment]
No bother, but I can't answer all of these questions without giving the solutions away. Just do your best and answer to the best of your ability. Good luck!
