### ISSUE TITLE
Question regarding how to submit of group proposal

### ISSUE THREAD

**Issue by taka1008** [macss-uml/General-Questions#3]
Just a quick clarification! 
For proposal of group project, "Final submissions should be a single PDF for the whole group submitted to Canvas." is written on Canvas, and this means we may submit a proposal on Canvas by only one member, not all members? 
 Thank you!

Takayuki

**Comment by pdwaggoner** [comment]
Hi @taka1008 - thanks for the question. That's correct! A single group member submitting a single proposal for the entire group is all that is required. Make sure all group members' names are on the proposal; everyone in the group will receive the same grade.
